version: "3.9"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: smartpatents-backend
    ports:
      - "5000:5000"
    env_file:
      - prod.env

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: smartpatents-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
