version: "3.9"

services:
  backend:
    build: ./api
    container_name: smartpatents-backend
    ports:
      - "5000:5000"
    env_file:
      - prod.env
    image:  kevin1179/smart-patents:latest

  frontend:
    build: .
    container_name: smartpatents-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    image:  kevin1179/smart-patents:latest
