version: "3.9"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: smartpatents-backend
    ports:
      - "5000:5000"
    env_file:
      - prod.env
    image: backend_image
    restart: unless-stopped

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: smartpatents-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    image: frontend_image
    restart: unless-stopped
