name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: 'Create env file'
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > prod.env
          cat prod.env

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ed25519
          chmod 600 ~/.ssh/ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Build, push, and run Docker image
        run: |
          docker compose build
          docker save -o frontend_image.tar smartpatents-frontend
          docker save -o backend_image.tar smartpatents-backend
          scp docker-compose.yml frontend_image.tar backend_image.tar ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:~/docker

          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << EOF
            cd docker
            docker load -i frontend_image.tar
            docker load -i backend_image.tar
            docker compose up -d
            docker image prune -f
          EOF
